FROM opensuse/leap:15.6
RUN zypper ref && \
    zypper --non-interactive dup && \
    zypper --non-interactive install man tar file sudo gzip tree git gh && \
    zypper clean --all

RUN echo "root:contraroot" | chpasswd
RUN groupadd sudo && useradd -m -s /bin/bash base && echo "base:alascoenctadas" | chpasswd && usermod -aG sudo base

WORKDIR /bin
RUN curl https://getmic.ro | bash
WORKDIR /


CMD ["sleep", "infinity"]
